### ISSUE TITLE
Ветка вопросов/ответов по проекту? 

### ISSUE THREAD

**Issue by KOVALcraft** [latecore-test/learning#11]

**Comment by ITSurgeon** [comment]
А что, у тебя не получается?

**Comment by KOVALcraft** [comment]
Если бы у меня не получалось, я бы не задавал вопрос про уполномоченного ))
Задам вопрос по другому, кто главный? кто решает что вопрос закрыт или закрыт неправильно...

**Comment by phgithubacc** [comment]
В данно случае ишью станет закрывать принимающая сторона.
Напреимер сейчас появится ишью "Требуется путь к папке с бандлом и ассетами к spa-html странице, возвращаемой пользователю". В данном случае это будет ишью, где "бэкенд" станет формирователем внутреннего контракта-мититехзадания, а "фронтенд" его испольнителем. Соответственно принимать решение о закрытие ишью (минитехзадания) по факту его исполнения, отклонения или уточнения будет бэкенд, тоесть я. 
В то же время когда появится контракт-техзадание от "фронтенда" к "бэкенду" с содержимым "нужны проверенные и одобренные версии npm-пакетов для фронтенд-ветки", исполнять это ишью стану я, но закрывать только Боря как принимающая сторона.
