### ISSUE TITLE
Входящие параметры для базы данных

### ISSUE THREAD

**Issue by KOVALcraft** [latecore-test/learning#13]

**Comment by KOVALcraft** [comment]
Входящие данные на сохранение в базу данных согласно "ТЗ":

1 Цена электричества                                                  (дробные числа, обязательно к заполнению)
2 Имя клиента                                                              (строка, обязательно к заполнению)
3 Адрес здания                                                             (строка, обязательно к заполнению)
4 Тип панели                                                                (строка, обязательно к заполнению)
5 Размер крыши                                                           (дробные числа, обязательно к заполнению)
6 Тип здания                                                                 (строка)
7 Угол наклона                                                             (целое число)
8 Направление                                                             (строка)


9 Дата КП                                                                      (дата, обязательно к заполнению)
10 Генерация электроэнергии (кВт/год)                     (массив, обязательно к заполнению)
11 Экономия (грн./год)                                                (массив, обязательно к заполнению)
12 Стоимость солнечной электростанции                 (целое число, обязательно к заполнению)
13 Среднегодовая генерация                                      (целое число, обязательно к заполнению)
14 Среднегодовой доход                                             (целое число, обязательно к заполнению)
15 Уменьшение выбросов СО2                                   (целое число, обязательно к заполнению)
16 Срок окупаемости                                                   (целое число, обязательно к заполнению)

если что не так, поправьте меня ...

**Comment by phgithubacc** [comment]
По ТЗ на входящих параметрах не хватает:
- Компания
- Адрес (компании)
- Имя менеджера
- Цель солнечной станции
- Энергопотребление дома

**Comment by KOVALcraft** [comment]
Принято, сохраняем все данные!

**Comment by phgithubacc** [comment]
Ишью тогда закрой.
Ты его открывал - тебе его закрывать.
