### ISSUE TITLE
Структура входящих с фронтенд-приложения данных

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/learning#17]
Какой тип запроса используется для передачи данных с фронтенд части приложения?
Какова структура передаваемых данных (название полей, тип данных, их взаимная вложенность)?
Каков тип содержимого http-запроса (джейсон, просто html-текст, что-нибудь другое)?

**Comment by Hlazman** [comment]
1. Тип запроса POST
2. companyFields:{
        company:null, //type: text
        addressCompany: null, //type: text
        nameManager:null //type: text
    },
    PanelField:{
        panelType: null, //type: text
    },
    ClientFields: {
        electricityPrice:null, //type: number
        goals: null, //type: text
        energyHouse: null, //type: range
        buildingType: null, //type: text
        angleTilt: null, //type: number
        forward: null, //type: text
    },
    Fn:{
        submit: noop() // function
    }
3. json
