### ISSUE TITLE
Модели и подключение к базе денных

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/learning#18]
Список названий моделей
Строение моделей с типами данных их полей
Как производится подключение базы данных к бэкенду (названи метода, набор входящих параметров, асинхронный/не асинхронный, что метод возвращает обртано)

**Comment by KOVALcraft** [comment]
#1 Список названий моделей:
- proposals.js

#2 Строение моделей с типами данных их полей:
https://app.diagrams.net/#HKOVALcraft%2Ftest%2Fmaster%2FkovalTEST%2F%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%203.0

#3 Как производится подключение базы данных к бэкенду:
Подключена облачная база данных mongodb
Использован npm-пакет mongoose
Подключение произведено по вынесенной в .env файл переменных окружения под именем MONGODB_URL 
Создан отдельный единый управляющий соединением с базой данных файл /database/index.js
В файле управления соединением с базой данных также передаётся модель.
метод - connection
способ - асинхронный

**Comment by phgithubacc** [comment]
Метод connection принимает какие-либо обязательные или необязательные параметры?
Возвращает ли данный метод что-нибудь при своем вызове (есть ли в нем return и если да, что что он возвращает)?

**Comment by KOVALcraft** [comment]
#1 
Метод connection принимает в себя url подключения к базе данных mongodb+srv://koval:151020qwer@cluster0.dnfvn.mongodb.net/Latecore-Test-Database
который включает в себя:
ссылка на облачную базу Mongoose Atlas
название базы данных Latecore-Test-Database
логин koval
пароль 151020qwer

так как мы используем подход с конфигурационным файлом:
url подключения к базе, хранится в конфигурационном файле .env под переменной MONGODB_URL который мы и передаем в метод connection

**Comment by KOVALcraft** [comment]
#2
нет, метод connection ничего не возвращает, кроме записи лога в терминале про корректное или некорректное подключение к базе
