### ISSUE TITLE
Данные из базы для формирования pdf-документа

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/learning#19]
Для формирования ответного pdf-документа требуются следующей набор данных, рабитых на блоки:
Модель Building
   - имя владельца здания (строка)
   - адрес здания (строка)
   - координата долготы здания (дробное число)
   - координата шиторы здания (дробное число)
   - цена электричества здания (дробное число)
   - энергопотребление здания (дробное число)
   - тип здания (строка)

Модель Panel
   - тип кристалла панели (строка)
   - кпд преобразования панели (дробное число)
   - описание панели (строка)
   - общая площадь, покрываемая панелями (дробное число)
   - угол наклона крыши или панелей на ней (целочисленное значение)
   - направление стороны света, к которой будут обращены панели (строка)
   - азимут направления стороны света, к которой будут обращены панели (челочисленное значение) 

Модель Manager
   - имя менеджера (строка)
   - имя компании менеджера (строка)
   - адрес компании менеджера (строка)
   - телефон компании менеджера или самого менеджера (строка)
   - почта компании менеджера или самого менеджера (строка)
   - путь к фото менеджера в рамках файловой системы (строка)

**Comment by KOVALcraft** [comment]
готово! запушил
