### ISSUE TITLE
Составить модели Пользователя, здания, конкретного кп

### ISSUE THREAD

**Issue by ITSurgeon** [latecore-test/learning#2]

**Comment by KOVALcraft** [comment]
Концепция базы данных 1.0 - на обсуждение

https://app.diagrams.net/#HKOVALcraft%2Ftest%2Fmaster%2F%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85

**Comment by KOVALcraft** [comment]
Переделал структуру базы данных

https://app.diagrams.net/#HKOVALcraft%2Ftest%2Fmaster%2F%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%202.0

на согласование

**Comment by ITSurgeon** [comment]
Пункт 3.4 не нужен

**Comment by KOVALcraft** [comment]
п. 3.4 убрал и апдейтнул на гит

**Comment by ITSurgeon** [comment]
Ну и все поля модели менеджера тогда тоже должны быть продублированы в модели кп

**Comment by KOVALcraft** [comment]
Наверное ты хотел добавить, что и поля модели Client тоже должны быть продублированы в модели КП ?

**Comment by KOVALcraft** [comment]
Перенес все поля в модель КП

**Comment by KOVALcraft** [comment]
Данный Issues ошибочный и вводит разработчиков в заблуждение, закрываю его за ненадобностью!
