### ISSUE TITLE
Подключить базу данных к проекту

### ISSUE THREAD

**Issue by KOVALcraft** [latecore-test/learning#9]

**Comment by KOVALcraft** [comment]
Просьба создать конфигурационный файл .env и добавить туда переменную MONGODB_URL=mongodb+srv://koval:151020qwer@cluster0.dnfvn.mongodb.net/Latecore-Test-Database

Файл подключения к базе данных создан

**Comment by ITSurgeon** [comment]
А ты внес 0.0.0.0 в белый список IP-адресов, чтоб был доступ к базе с любого IP ?

**Comment by KOVALcraft** [comment]
Уже внёс)))

**Comment by phgithubacc** [comment]
Сделал в своей ветке. Посмостри мой последний пуш в нее. Если вопросов нет, закрой ишью.

**Comment by KOVALcraft** [comment]
Закрываю
